name: Build and Deploy to GitHub Pages

on:
  push:
    branches:
      - main

permissions:
  contents: write

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      # set up Go
      - uses: actions/setup-go@v3
        with:
          go-version: '1.18'
      - run: go version

      # set up Node
      - uses: actions/setup-node@v3
        with:
          node-version: 16
      - run: node -v

      - name: Install dependencies
        run: |
          apt install hugo
          npm install

      - name: Build
        run: bin/build

      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: dist
